"""update metadata model

Revision ID: 4664561e6c1c
Revises: bdf0282f24b4
Create Date: 2026-07-12 16:49:44.188434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4664561e6c1c'
down_revision: Union[str, Sequence[str], None] = 'bdf0282f24b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('compression', sa.String(), nullable=True))
    op.add_column('file', sa.Column('file_type', sa.String(), nullable=False, server_default='media'))
    op.alter_column(
        "file",
        "file_type",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_type')
    op.drop_column('file', 'compression')
    # ### end Alembic commands ###
